import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Plus, Pencil, Trash2, X, Package, ChevronDown, Sparkles, ArrowUpDown, LayoutGrid, List, Download, CheckCircle2, AlertCircle, ReceiptText, Banknote, WalletCards, CalendarDays, Minus, History, ShoppingCart} from 'lucide-react';
import './styles.css';

const initialProducts = [
['HUEVOS x6',1000,'Huevos'],['HUEVOS BOLITA',3300,'Huevos'],['HUEVOS MEDIANOS',4500,'Huevos'],['HUEVOS GRANDES',5200,'Huevos'],['HUEVOS SUPER',6500,'Huevos'],
['MIEL OSCURA 1/2 KG',3800,'Miel y dulces'],['MIEL OSCURA 1/4 KG',2300,'Miel y dulces'],['MIEL CLARA 1/2 KG',3500,'Miel y dulces'],['MIEL CLARA 1/4 KG',2100,'Miel y dulces'],['ALCAYOTA',4500,'Miel y dulces'],['JALEA MEMBRILLO',5200,'Miel y dulces'],
['NUEZ',2400,'Frutos secos'],['ALMENDRA',3000,'Frutos secos'],['PASAS',2000,'Frutos secos'],['FRUTOS SECOS',2000,'Frutos secos'],['MAIZ FRITO',2500,'Frutos secos'],
['ACEITE 1/2 LITROS',9500,'Aceites'],['ACEITE 1 LITRO',16500,'Aceites'],['ACEITE 5 LITROS',69500,'Aceites'],['SALSA',1500,'Conservas'],['SALSA PACK DE 8',12000,'Conservas'],
['ACEITUNAS VERDES 1/2 KG',3900,'Conservas'],['ACEITUNAS VERDES 1 KG',5800,'Conservas'],['ACEITUNAS VERDES 5 KG',22800,'Conservas'],['ACEITUNAS NEGRAS 1/2 KG',5500,'Conservas'],['ACEITUNAS NEGRAS 1 KG',8200,'Conservas'],['PICKLES MIXTOS',3900,'Conservas'],['CEBOLLITAS',3900,'Conservas'],['PEPINILLOS CHICOS',0,'Conservas'],['PEPINILLOS GRANDES',0,'Conservas'],['TOMATE DESECADO',3000,'Conservas'],
['PAPAS FRITAS BOLSA GRANDE',15500,'Snacks'],['PAPAS FRITAS BOLSA CHICA',1500,'Snacks'],['CHICITOS BOLSA GRANDE',7000,'Snacks'],['CHICITOS BOLSA CHICA',1500,'Snacks'],['CONITOS BOLSA GRANDE',7000,'Snacks'],['CONITOS BOLSA CHICA',1500,'Snacks'],['MANI SALADO BOLSA GRANDE',6000,'Snacks'],['MANI SALADO BOLSA CHICA',1500,'Snacks'],['PALITOS BOLSA GRANDE',7000,'Snacks'],['PALITOS BOLSA CHICA',1500,'Snacks'],['MANI SABORIZADO BOLSA GRANDE',19000,'Snacks'],['MANI SABORIZADO BOLSA CHICA',1500,'Snacks'],['MANI CASCARA BOLSA GRANDE',8500,'Snacks'],['MANI CASCARA BOLSA CHICA',1500,'Snacks'],['TUTUCAS BOLSA GRANDE',9000,'Snacks'],['TUTUCAS BOLSA CHICA',1500,'Snacks'],
['DULCE DE MEMBRILLO ROJO 500grs',4200,'Miel y dulces'],['DULCE DE MEMBRILLO 1Kg',5400,'Miel y dulces'],['DULCE DE MEMBRILLO 5Kgs',13700,'Miel y dulces'],['DULCE DE BATATA 500grs',3900,'Miel y dulces'],['MERMELADA DE MEMBRILLO',0,'Miel y dulces'],['MERMELADA DE DURAZNO',4000,'Miel y dulces'],['MERMELADA DE TOMATE',0,'Miel y dulces'],['BATATITAS',0,'Miel y dulces'],['QUINOTOS',0,'Miel y dulces'],['DULCE DE JALEA',4200,'Miel y dulces'],['OREJONES',0,'Miel y dulces']
].map(([name,price,category],i)=>({id:i+1,name,price,category}));

const categoryIcon={Huevos:'🥚','Miel y dulces':'🍯','Frutos secos':'🥜',Aceites:'🫗',Conservas:'🫒',Snacks:'🍟',Almacén:'🧉',Artesanales:'🍪'};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateLabel=date=>new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${date}T12:00:00`));
const dateShort=date=>new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${date}T12:00:00`));

function App(){
 const [products,setProducts]=useState(()=>{try{return JSON.parse(localStorage.getItem('bartol-products'))||initialProducts}catch{return initialProducts}});
 const [sales,setSales]=useState(()=>{try{return JSON.parse(localStorage.getItem('bartol-sales'))||[]}catch{return []}});
 const [section,setSection]=useState('products');
 const [search,setSearch]=useState(''); const [category,setCategory]=useState('Todos'); const [sort,setSort]=useState('name-asc'); const [viewMode,setViewMode]=useState('grid');
 const [modal,setModal]=useState(null); const [form,setForm]=useState({name:'',price:'',category:'Huevos'}); const [newCategory,setNewCategory]=useState(''); const [confirm,setConfirm]=useState(null); const [notification,setNotification]=useState(null);
 const [saleDate,setSaleDate]=useState(todayISO()); const [saleModal,setSaleModal]=useState(null); const [saleForm,setSaleForm]=useState({productId:'',quantity:1,unitPrice:'',description:'',paymentMethod:'Efectivo'}); const [saleProductSearch,setSaleProductSearch]=useState(''); const [historyDate,setHistoryDate]=useState(todayISO());
 useEffect(()=>localStorage.setItem('bartol-products',JSON.stringify(products)),[products]);
 useEffect(()=>localStorage.setItem('bartol-sales',JSON.stringify(sales)),[sales]);
 useEffect(()=>{if(notification){const t=setTimeout(()=>setNotification(null),2800);return()=>clearTimeout(t)}},[notification]);
 const categories=['Todos','Huevos','Miel y dulces','Frutos secos','Aceites','Conservas','Snacks','Almacén','Artesanales',...new Set(products.map(p=>p.category))].filter((c,i,a)=>a.indexOf(c)===i);
 const filtered=useMemo(()=>{const list=products.filter(p=>(category==='Todos'||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase()));return [...list].sort((a,b)=>sort==='name-desc'?b.name.localeCompare(a.name):sort==='price-asc'?a.price-b.price:sort==='price-desc'?b.price-a.price:a.name.localeCompare(b.name))},[products,category,search,sort]);
 const daySales=useMemo(()=>sales.filter(s=>s.date===saleDate),[sales,saleDate]);
 const historySales=useMemo(()=>sales.filter(s=>s.date===historyDate),[sales,historyDate]);
 const totals=useMemo(()=>daySales.reduce((acc,s)=>{acc.total+=Number(s.total)||0;if(s.paymentMethod==='Mercado Pago')acc.mp+=Number(s.total)||0;else acc.cash+=Number(s.total)||0;return acc},{total:0,cash:0,mp:0}),[daySales]);
 const showNotification=(message,type='success')=>setNotification({message,type});
 const openAdd=()=>{setForm({name:'',price:'',category:categories.find(c=>c!=='Todos')||'Huevos'});setNewCategory('');setModal('add')};
 const openEdit=p=>{setForm({name:p.name,price:p.price,category:p.category});setNewCategory('');setModal(p)};
 const save=e=>{e.preventDefault();const name=form.name.trim();if(!name)return;const price=Math.max(0,Number(form.price)||0);const selectedCategory=form.category==='__new__'?newCategory.trim():form.category;if(!selectedCategory)return;if(modal==='add'){setProducts(ps=>[...ps,{id:Date.now(),name,price,category:selectedCategory}]);showNotification('Producto agregado')}else{setProducts(ps=>ps.map(p=>p.id===modal.id?{...p,name,price,category:selectedCategory}:p));showNotification('Producto actualizado')}setModal(null);setNewCategory('')};
 const remove=()=>{setProducts(ps=>ps.filter(p=>p.id!==confirm.id));setConfirm(null);showNotification('Producto eliminado','warning')};
 const clearSearch=()=>setSearch('');
 const exportPrices=()=>{const lines=['DISTRIBUIDORA BARTOL','LISTA DE PRECIOS',`Fecha: ${dateShort(todayISO())}`,''];categories.filter(c=>c!=='Todos').forEach(c=>{lines.push(`--- ${c.toUpperCase()} ---`);products.filter(p=>p.category===c).sort((a,b)=>a.name.localeCompare(b.name)).forEach(p=>lines.push(`${p.name} — ${p.price===0?'PRECIO PENDIENTE':money(p.price)}`));lines.push('')});const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lista-precios-bartol-${todayISO()}.txt`;a.click();URL.revokeObjectURL(a.href);showNotification('Lista de precios exportada')};
 const openSaleAdd=()=>{setSaleForm({productId:'',quantity:1,unitPrice:'',description:'',paymentMethod:'Efectivo'});setSaleProductSearch('');setSaleModal('add')};
 const openSaleEdit=s=>{setSaleForm({productId:s.productId,quantity:s.quantity,unitPrice:s.unitPrice,description:s.description,paymentMethod:s.paymentMethod});setSaleProductSearch(s.productName)};
 const saleProduct=products.find(p=>String(p.id)===String(saleForm.productId));
 const saleTotal=(Number(saleForm.quantity)||0)*(Number(saleForm.unitPrice)||0);
 const handleSaleProduct=id=>{const p=products.find(x=>String(x.id)===String(id));setSaleForm(f=>({...f,productId:id,unitPrice:p?.price||'',description:p?.name||''}));setSaleProductSearch(p?.name||'')};
 const saleProductMatches=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(saleProductSearch.toLowerCase())),[products,saleProductSearch]);
 const saveSale=e=>{e.preventDefault();const quantity=Number(saleForm.quantity);const unitPrice=Number(saleForm.unitPrice);if(!saleForm.productId||quantity<=0||unitPrice<0)return;const product=products.find(p=>String(p.id)===String(saleForm.productId));const item={id:saleModal==='add'?Date.now():saleModal.id,date:saleModal==='add'?saleDate:saleModal.date,productId:product.id,productName:product.name,description:saleForm.description.trim()||product.name,quantity,unitPrice,total:quantity*unitPrice,paymentMethod:saleForm.paymentMethod,createdAt:saleModal==='add'?new Date().toISOString():saleModal.createdAt};if(saleModal==='add'){setSales(ss=>[...ss,item]);showNotification('Venta registrada')}else{setSales(ss=>ss.map(s=>s.id===saleModal.id?item:s));showNotification('Venta actualizada')}setSaleModal(null)};
 const removeSale=s=>{setConfirm({type:'sale',...s})};
 const removeConfirmed=()=>{if(confirm.type==='sale'){setSales(ss=>ss.filter(s=>s.id!==confirm.id));setConfirm(null);showNotification('Venta eliminada','warning')}else remove()};
 const exportDay=()=>{const lines=[`DISTRIBUIDORA BARTOL`,`VENTAS — ${dateLabel(saleDate)}`,''];daySales.forEach(s=>lines.push(`${s.quantity} x ${s.description} — ${money(s.total)} — ${s.paymentMethod}`));lines.push('',`TOTAL EFECTIVO: ${money(totals.cash)}`,`TOTAL MERCADO PAGO: ${money(totals.mp)}`,`TOTAL DEL DÍA: ${money(totals.total)}`);const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ventas-bartol-${saleDate}.txt`;a.click();URL.revokeObjectURL(a.href);showNotification('Ventas exportadas')};
 return <div className="app">
   <div className="floating">🥚</div><div className="floating f2">🍯</div><div className="floating f3">🥜</div><div className="grain"/>
   <header><div className="brand"><div className="logo">B</div><div><strong>DISTRIBUIDORA BARTOL</strong><span>Gestión del negocio</span></div></div><div className="header-actions">{section==='products'&&<button className="secondary-action" onClick={exportPrices}><Download size={17}/> Exportar Precios</button>} {section==='sales'&&<button className="secondary-action" onClick={exportDay}><Download size={17}/> Exportar día</button>}<button className="add" onClick={section==='products'?openAdd:openSaleAdd}><Plus size={19}/> {section==='products'?'Nuevo producto':'Registrar venta'}</button></div></header>
   <main>
    <nav className="section-switch"><button className={section==='products'?'active':''} onClick={()=>setSection('products')}><Package size={18}/> Productos</button><button className={section==='sales'?'active':''} onClick={()=>setSection('sales')}><ReceiptText size={18}/> Ventas</button></nav>
    {section==='products'?<>
      <section className="hero"><div><div className="eyebrow"><Sparkles size={15}/> LISTA DE PRECIOS</div><h1>Todo Bartol,<br/><em>en un solo lugar.</em></h1><p>Buscá, consultá y actualizá tus productos en segundos.</p></div><div className="hero-egg">🥚</div></section>
      <section className="toolbar"><div className="search"><Search size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar productos..."/><button className="clear-search" onClick={clearSearch} title="Limpiar búsqueda" disabled={!search}><X size={16}/></button></div><div className="categories">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c!=='Todos'&&categoryIcon[c]} {c}</button>)}</div></section>
      <div className="summary"><span><Package size={17}/><b>{filtered.length}</b> productos</span><div className="view-tools"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name-asc">Nombre A → Z</option><option value="name-desc">Nombre Z → A</option><option value="price-asc">Precio menor → mayor</option><option value="price-desc">Precio mayor → menor</option></select><div className="view-switch"><button className={viewMode==='grid'?'active':''} onClick={()=>setViewMode('grid')} title="Vista grilla"><LayoutGrid size={16}/></button><button className={viewMode==='list'?'active':''} onClick={()=>setViewMode('list')} title="Vista lista"><List size={16}/></button></div></div></div>
      {filtered.length===0?<div className="empty"><div>🔎</div><h2>No encontramos productos</h2><p>Probá con otro nombre o categoría.</p></div>:<div className={viewMode==='grid'?'grid':'list-view'}>{filtered.map(p=><article className="card" key={p.id}><div className="actions"><button title="Editar" onClick={()=>openEdit(p)}><Pencil size={16}/></button><button title="Eliminar" onClick={()=>setConfirm(p)}><Trash2 size={16}/></button></div><div className="product-info"><h2>{p.name}</h2><div className={p.price===0?'price pending':'price'}>{p.price===0?<><AlertCircle size={14}/> Precio pendiente</>:money(p.price)}</div></div><span className="tag">{categoryIcon[p.category]||'📦'} {p.category}</span></article>)}</div>}
    </>:<>
      
      <section className="sales-summary"><div className="stat total"><span>Total del día</span><strong>{money(totals.total)}</strong><small>{daySales.length} {daySales.length===1?'venta':'ventas'}</small></div><div className="stat"><span><Banknote size={16}/> Efectivo</span><strong>{money(totals.cash)}</strong></div><div className="stat"><span><WalletCards size={16}/> Mercado Pago</span><strong>{money(totals.mp)}</strong></div></section>
      <div className="sales-title"><h2>{dateLabel(saleDate)}</h2><button className="sale-add" onClick={openSaleAdd}><Plus size={17}/> Nueva venta</button></div>
      {daySales.length===0?<div className="empty sales-empty"><div>🧾</div><h2>Todavía no hay ventas</h2><p>Registrá la primera venta de este día para empezar a llevar el control.</p><button className="sale-add" onClick={openSaleAdd}><Plus size={17}/> Registrar venta</button></div>:<div className="sales-list">{daySales.map(s=><article className="sale-card" key={s.id}><div className="sale-main"><div className="sale-qty">{s.quantity}×</div><div><h3>{s.productName}</h3><p>{s.description!==s.productName?s.description:'Venta registrada'} · {money(s.unitPrice)} c/u</p></div></div><div className="sale-payment"><span className={s.paymentMethod==='Mercado Pago'?'mp':'cash'}>{s.paymentMethod==='Mercado Pago'?<WalletCards size={14}/>:<Banknote size={14}/>} {s.paymentMethod}</span><strong>{money(s.total)}</strong></div><div className="sale-actions"><button onClick={()=>{openSaleEdit(s);setSaleModal(s)}} title="Editar"><Pencil size={15}/></button><button onClick={()=>removeSale(s)} title="Eliminar"><Trash2 size={15}/></button></div></article>)}</div>}
      <section className="history-panel"><div><span className="eyebrow"><History size={14}/> HISTORIAL</span><h2>Consultar ventas de otro día</h2><p>Elegí una fecha para revisar lo registrado.</p></div><div className="history-form"><input type="date" value={historyDate} onChange={e=>setHistoryDate(e.target.value)}/><button onClick={()=>setSaleDate(historyDate)}>Ver día</button></div></section>
    </>}
   </main>
   <footer>Distribuidora Bartol <span>•</span> Gestión simple para el día a día</footer>
   {modal&&<div className="overlay"><form className="modal" onSubmit={save}><button type="button" className="close" onClick={()=>setModal(null)}><X/></button><div className="modal-icon">{modal==='add'?<Plus/>:<Pencil/>}</div><h2>{modal==='add'?'Nuevo producto':'Editar producto'}</h2><p>{modal==='add'?'Agregá un producto a tu lista.':'Modificá los datos del producto.'}</p><label>Nombre<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej. Miel de eucalipto 1 KG"/></label><label>Precio<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="0"/></label><label>Categoría<div className="select"><select value={form.category} onChange={e=>{setForm({...form,category:e.target.value});if(e.target.value!=='__new__')setNewCategory('')}}>{categories.filter(c=>c!=='Todos').map(c=><option key={c}>{c}</option>)}<option value="__new__">＋ Nueva categoría</option></select><ChevronDown size={17}/></div></label>{form.category==='__new__'&&<label>Nueva categoría<input autoFocus value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Ej. Almacén"/></label>}<div className="modal-actions"><button type="button" className="cancel" onClick={()=>setModal(null)}>Cancelar</button><button className="save">Guardar producto</button></div></form></div>}
   {saleModal&&<div className="overlay"><form className="modal sale-modal" onSubmit={saveSale}><button type="button" className="close" onClick={()=>setSaleModal(null)}><X/></button><div className="modal-icon sale-icon"><ReceiptText/></div><h2>{saleModal==='add'?'Registrar venta':'Editar venta'}</h2><p>Podés cambiar el precio manualmente según el descuento acordado con el cliente.</p><label>Producto<div className="product-picker"><div className="product-search"><Search size={16}/><input value={saleProductSearch} onChange={e=>setSaleProductSearch(e.target.value)} placeholder="Buscar producto..." autoComplete="off"/></div><div className="product-options">{saleProductSearch.trim()&&(saleProductMatches.length===0?<div className="product-no-results">No se encontró ningún producto.</div>:saleProductMatches.map(p=><button type="button" key={p.id} className={String(p.id)===String(saleForm.productId)?'selected':''} onClick={()=>handleSaleProduct(p.id)}><span>{p.name}</span><small>{p.price===0?'Precio pendiente':money(p.price)}</small></button>))}</div></div></label><div className="two-fields"><label>Cantidad<input type="number" min="1" step="1" value={saleForm.quantity} onChange={e=>setSaleForm({...saleForm,quantity:e.target.value})}/></label><label>Precio cobrado c/u<input type="number" min="0" step="1" value={saleForm.unitPrice} onChange={e=>setSaleForm({...saleForm,unitPrice:e.target.value})}/></label></div><label>Descripción / detalle<input value={saleForm.description} onChange={e=>setSaleForm({...saleForm,description:e.target.value})} placeholder="Ej. 2 cartones huevos bolita"/></label><label>Forma de pago<div className="payment-options"><button type="button" className={saleForm.paymentMethod==='Efectivo'?'selected':''} onClick={()=>setSaleForm({...saleForm,paymentMethod:'Efectivo'})}><Banknote size={18}/> Efectivo</button><button type="button" className={saleForm.paymentMethod==='Mercado Pago'?'selected':''} onClick={()=>setSaleForm({...saleForm,paymentMethod:'Mercado Pago'})}><WalletCards size={18}/> Mercado Pago</button></div></label><div className="sale-total-box"><span>Total cobrado</span><strong>{money(saleTotal)}</strong></div><div className="modal-actions"><button type="button" className="cancel" onClick={()=>setSaleModal(null)}>Cancelar</button><button className="save">{saleModal==='add'?'Registrar venta':'Guardar cambios'}</button></div></form></div>}
   {confirm&&<div className="overlay"><div className="confirm"><div className="danger"><Trash2/></div><h2>¿Eliminar {confirm.type==='sale'?'venta':'producto'}?</h2><p>{confirm.type==='sale'?<>Vas a eliminar la venta de <b>{confirm.description}</b> por <b>{money(confirm.total)}</b>.</>:<>Vas a eliminar <b>{confirm.name}</b>. Esta acción no se puede deshacer.</>}</p><div className="modal-actions"><button className="cancel" onClick={()=>setConfirm(null)}>Cancelar</button><button className="delete" onClick={removeConfirmed}>Eliminar</button></div></div></div>}
   {notification&&<div className={`toast ${notification.type}`}><CheckCircle2 size={18}/>{notification.message}</div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
